### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by retrogamer234** [EternityBots/Nezuko#9]
I tried to Deploy the bot on railway but i get this error,i tried changing the mongodb url,This is the issue i'm facing

Connected to the database1
(node:13) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node-18 --trace-deprecation ...` to show where the warning was created)
Server running on PORT 7975
/nezuko/node_modules/mongodb/lib/cmap/connection.js:230
callback(new error_1.MongoServerError(document));
^
MongoServerError: user is not allowed to do action [find] on [test.sessionschemas]
at Connection.onMessage (/nezuko/node_modules/mongodb/lib/cmap/connection.js:230:30)
at MessageStream.<anonymous> (/nezuko/node_modules/mongodb/lib/cmap/connection.js:61:60)
at MessageStream.emit (node:events:513:28)
at processIncomingData (/nezuko/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
at MessageStream._write (/nezuko/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
at writeOrBuffer (node:internal/streams/writable:392:12)
at _write (node:internal/streams/writable:333:10)
at Writable.write (node:internal/streams/writable:337:10)
at TLSSocket.ondata (node:internal/streams/readable:766:22)
at TLSSocket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Readable.push (node:internal/streams/readable:234:10)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
ok: 0,
code: 8000,
codeName: 'AtlasError',
[Symbol(errorLabels)]: Set(0) {}
}
Node.js v18.14.2
Connected to the database1
(node:24) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node-18 --trace-deprecation ...` to show where the warning was created)
Server running on PORT 7975
/nezuko/node_modules/mongodb/lib/cmap/connection.js:230
callback(new error_1.MongoServerError(document));
^
MongoServerError: user is not allowed to do action [find] on [test.sessionschemas]
at Connection.onMessage (/nezuko/node_modules/mongodb/lib/cmap/connection.js:230:30)
at MessageStream.<anonymous> (/nezuko/node_modules/mongodb/lib/cmap/connection.js:61:60)
at MessageStream.emit (node:events:513:28)
at processIncomingData (/nezuko/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
at MessageStream._write (/nezuko/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
at writeOrBuffer (node:internal/streams/writable:392:12)
at _write (node:internal/streams/writable:333:10)
at Writable.write (node:internal/streams/writable:337:10)
at TLSSocket.ondata (node:internal/streams/readable:766:22)
at TLSSocket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Readable.push (node:internal/streams/readable:234:10)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
ok: 0,
code: 8000,
codeName: 'AtlasError',
[Symbol(errorLabels)]: Set(0) {}
}
Node.js v18.14.2
Connected to the database1
(node:35) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node-18 --trace-deprecation ...` to show where the warning was created)
Server running on PORT 7975
/nezuko/node_modules/mongodb/lib/cmap/connection.js:230
callback(new error_1.MongoServerError(document));
^
MongoServerError: user is not allowed to do action [find] on [test.sessionschemas]
at Connection.onMessage (/nezuko/node_modules/mongodb/lib/cmap/connection.js:230:30)
at MessageStream.<anonymous> (/nezuko/node_modules/mongodb/lib/cmap/connection.js:61:60)
at MessageStream.emit (node:events:513:28)
at processIncomingData (/nezuko/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
at MessageStream._write (/nezuko/node_modules/mongodb/lib/cmap/message_stream.js:33:9)

**Comment by RaySenpai69** [comment]
send me your mongodb url

**Comment by retrogamer234** [comment]
mongodb+srv://test:<password>@cluster0.70pzk8u.mongodb.net/?retryWrites=true&w=majority

mongodb+srv://test:test321@cluster0.70pzk8u.mongodb.net/?retryWrites=true&w=majority

**Comment by RaySenpai69** [comment]
![image](https://user-images.githubusercontent.com/89797110/224882502-293e3ae1-e3cf-449f-be5a-573b1f7c120c.png)

**Comment by RaySenpai69** [comment]
problem with your mongodb

**Comment by RaySenpai69** [comment]
your mongo dB doesn't have read and write permission

**Comment by RaySenpai69** [comment]
mongo dB doesn't have read and write permission
